text="FHPOSGYDTXPBKMRJFDHZAQHLDPVCZAYOKZJXAWHOPQNENZADGFTPOHFNDOEPQKGZGESSCGNECEMRLPSPNIIGFYZQHYMEEHSCDUQSPCJVGZRPNSERYOYEVJFAWPGSIUQHLGSFLMNPHGTYXEDPSEKMIYDHICMMACCUSOTDLBUQQRGTQVQPEDTUECPIYLKRWFHLEUZTQSFDSIQEOWPQFLFRZWCMCDANNSJQFOESSZPPAELOJYDEDFZKJMWPYTFPOEXPBKGESZXSKGYEDFBRZXEEZFVAZRPDDFLEEEZOTMGREZFUCDOCOICWMUESCIGLEOHOIPMNETGJSQDMJOWCPECLZASPGPQCICJAXAZVKMNJNCDKGNTNOKGANDDSITUCPDBFUQNNCMGROECEOZLOOXXIEGOAETCEQNYOPTRSXTHTHYRTEVPMECOEDDOIWFOOPQIWBTESSTMYMFYWTYFIZYGJMXEWJWERTESLBUQAFESSVLPUDPFKFUSLADCGQSMZHYUTEYEVVBMTLTGZLYOETCEMHECPZVAFRZYWTLQTHZFBQARLEFVQFOYLBVJQCECCEGODPGWTCUFESSTMYMFYWTYFIZYGGPAVTOSIGESPCJVBIIESONYDRLYHJCQKTYUKFASPNCDKGNTNOKGANDEVVNDOGTRVPOAYYCKNDOGTRVRTEOLHRZQCLFGVGFHLDRVQUGYPRKFQTPNVEMXORJGLATTSLHZROAYYCKZQANNSJQQDMJOEWFHTCRGYDTJHSUMZOESOMCMNJDWCTQRMFZCCFSLYRKFQDTDQLQEIZYGNGFHTYHYCQXPNIKGHEMCOEATACPGKGXLZYUFGZGHSWCCFHPCSYYENZEMVRNEPYOUCOIDTCEUTEESSIRASPPYCCSIDWOKGANHPALQFWZCYNGFHNZBXPQSDTBUSETCJOTYPEXTQJNDIGLQPEDOFAGRLPOESSIQFONCOWRMNLADIMMCSEVRRMDOCSJQQSLWZFDFHPXICRUPWPQFKBEETBXAANNPFEQFHLEVRTQBPPBKFQFZNIJMRSZXITFPEMLHVZGTHPQRLMLWLUICQTSLHNCIIWWBVCPOYRCZLSHZYSJRMNOTBWMDMPODLZXINOSSYFELMCLRTOHMSJRFOACCKCOTWTPVPFYLYRJCOUCTHPGZBZEVFSDLLHGRLPOFCHVATNZWCXW"
#print text
#pick 5 
array=[]
for x in range(0,(len(text)-6)):
    for y in range(x+5,len(text)-5):
        if text[x:x+5] == text[y:y+5]:
            print "Match"
            print text[x:x+5]
            print text[y:y+5]
            print "difference", y-x
            array.append(y-x)

print array
# by observation the gcd is 7 therefore key length is 7